### ISSUE TITLE
[BUG]RUN ERROR

### ISSUE THREAD

**Issue by martjay** [Dadangdut33/Speech-Translate#17]
Traceback (most recent call last):
  File "Main.py", line 969, in <module>
  File "Main.py", line 247, in __init__
  File "speech_translate\utils\Record.py", line 35, in getInputDevices
  File "sounddevice.py", line 564, in query_devices
  File "sounddevice.py", line 564, in <genexpr>
  File "sounddevice.py", line 578, in query_devices
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
[20716] Failed to execute script 'Main' due to unhandled exception!

OS: windows 11 pro x64

Python: 3.10.6

GUI: GPU version last

**Comment by Dadangdut33** [comment]
hmm, what is your sounddevice version?

**Comment by Dadangdut33** [comment]
i will close this for now until you provide more context/details as i couldn't replicate the problem
