### ISSUE TITLE
[BUG] weird translation error

### ISSUE THREAD

**Issue by LucekLukasz** [Dadangdut33/Speech-Translate#25]
in version 1.1 everything worked, in 1.2 these errors in the log:

2023-03-27 16:56:10,128 INFO    - Console window hidden. If it is not hidden (only minimized), try changing your default windows terminal to windows cmd. (Main.py:50) [MainThread]
2023-03-27 16:56:10,128 INFO    - Booting up... (Main.py:1019) [MainThread]
2023-03-27 16:56:10,254 DEBUG   - Available Theme to use: ['vista', 'sv-light', 'sv-dark'] (Main.py:157) [MainThread]
2023-03-27 16:56:10,254 DEBUG   - Setting theme: sv-dark (Style.py:28) [MainThread]
2023-03-27 16:56:10,273 DEBUG   - Setting custom dark theme style (Style.py:49) [MainThread]
2023-03-27 16:56:13,442 INFO    - Checking for update on start (About.py:100) [MainThread]
2023-03-27 16:56:14,118 INFO    - Checking for update... (About.py:125) [MainThread]
2023-03-27 16:56:14,431 INFO    - No update available (About.py:145) [Thread-5 (req_update_check)]
2023-03-27 16:56:35,352 INFO    - Start Process (FILE) (Record.py:1015) [Thread-6 (from_file)]
2023-03-27 16:56:35,399 DEBUG   - Translating... (Record.py:701) [Thread-7 (cancellable_tl)]
2023-03-27 16:56:35,400 DEBUG   - Translating with whisper (Record.py:714) [Thread-7 (cancellable_tl)]
2023-03-27 16:56:35,406 DEBUG   - Source Language: polish (Record.py:715) [Thread-7 (cancellable_tl)]
2023-03-27 16:58:48,499 ERROR   - string indices must be integers (Record.py:828) [Thread-7 (cancellable_tl)]
Traceback (most recent call last):
  File "speech_translate\utils\Record.py", line 759, in cancellable_tl
  File "speech_translate\utils\Helper_Whisper.py", line 44, in whisper_result_to_srt
TypeError: string indices must be integers
TL Wait (133.34s)

???

**Comment by Dadangdut33** [comment]
sorry, it seems like i put the wrong variable into the `whisper_result_to_srt` function. That's why it make that error

will fix asap

**Comment by Dadangdut33** [comment]
This should be fixed in the next release version (1.2.2)
