### ISSUE TITLE
[BUG]Can't open and run normally

### ISSUE THREAD

**Issue by despairTK** [Dadangdut33/Speech-Translate#30]
**Describe the bug**
2023-04-12 00:57:36,936 INFO    - Console window hidden. If it is not hidden (only minimized), try changing your default windows terminal to windows cmd. (Main.py:51) [MainThread]
test
2023-04-12 00:57:36,936 INFO    - Booting up... (Main.py:1050) [MainThread]
2023-04-12 00:57:37,002 DEBUG   - Available Theme to use: ['vista', 'sv-light', 'sv-dark'] (Main.py:159) [MainThread]
2023-04-12 00:57:37,002 DEBUG   - Setting theme: sv-dark (Style.py:28) [MainThread]
2023-04-12 00:57:37,014 DEBUG   - Setting custom dark theme style (Style.py:49) [MainThread]
Traceback (most recent call last):
  File "Main.py", line 1053, in <module>
  File "Main.py", line 404, in __init__
  File "Main.py", line 541, in onInit
  File "Main.py", line 546, in cb_mic_init
  File "Main.py", line 564, in label_microphone_Rclick
  File "speech_translate\utils\Record.py", line 65, in getDefaultInputDevice
  File "sounddevice.py", line 569, in query_devices
sounddevice.PortAudioError: Error querying device -1

**To Reproduce**
1. Run SpeechTranslate.exe directly

**Expected behavior**
Download SpeechTranslate 1.2.2 GPU, run SpeechTranslate.exe directly after decompression

**Screenshots**
![QQ截图20230412010319](https://user-images.githubusercontent.com/111871110/231236926-cb9fd609-ae1b-417a-b615-0c88927e4403.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Python Version : 3.10.9
 - GPU：RTX 4090

**Additional context**
Interestingly, I can open the software normally on my other windows 10 computer.

**Comment by k566o** [comment]
It doesn't work for me either, does not show main window, I only see it in task bar, but right clicking on it, and choosing any option does nothing. I have to force kill it from task manager.

**Comment by Dadangdut33** [comment]
hmm, do you guys not have any audio input device connected?

**Comment by despairTK** [comment]
> 嗯，你们没有连接任何音频输入设备吗？

Yes, there is no audio input device connected, my other working laptop is a laptop with its own microphone, my desktop does not have a microphone connected. I just use it to transcribe some videos, can the next update allow the program to run on devices without any audio input?

**Comment by Dadangdut33** [comment]
> Yes, there is no audio input device connected, my other working laptop is a laptop with its own microphone, my desktop does not have a microphone connected. I just use it to transcribe some videos, can the next update allow the program to run on devices without any audio input?

Ok, thanks for the information, i'll upload a fix / update soon

**Comment by Dadangdut33** [comment]
Check out the [new release](https://github.com/Dadangdut33/Speech-Translate/releases/tag/1.2.3), it should be fixed now
