### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by romesilverio** [Dadangdut33/Speech-Translate#45]
...
i am getting the above error when importing the file/s.

**Comment by romesilverio** [comment]
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2023-09-07 10:59:29,218 INFO    - Booting up... (Main.py:959) [MainThread]
2023-09-07 10:59:29,218 DEBUG   - Got console window (Main.py:962) [MainThread]
2023-09-07 10:59:32,980 INFO    - Checking for update on start (About.py:108) [MainThread]
2023-09-07 10:59:33,115 INFO    - Checking for update... (About.py:133) [MainThread]
2023-09-07 10:59:33,611 INFO    - New version found: 1.2.3 (About.py:146) [Thread-3 (req_update_check)]
2023-09-07 10:59:39,332 INFO    - Start Process (FILE) (Record.py:848) [Thread-5 (from_file)]
2023-09-07 10:59:39,545 INFO    - -------------------------------------------------- (Record.py:761) [Thread-6 (multiproc_tc)]
2023-09-07 10:59:39,545 INFO    - Transcribing Audio: C:/Users/rome.silverio/Downloads/801-900/PH_SNX_Pfizer_XCITE_9000_Z1_Eng.wav (Record.py:762) [Thread-6 (multiproc_tc)]
2023-09-07 10:59:39,545 DEBUG   - Source Language: Auto (Record.py:771) [Thread-6 (multiproc_tc)]
Import-Module : The network path was not found
At C:\Users\rome.silverio\OneDrive - Cardinal Health\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:1
char:1
+ Import-Module -Fullyqualifiedname "\\wpec5009cmtsk01\eitscl2\psmodule ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.ImportModuleCommand

whisper\transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
Exception in thread Thread-7 (run_threaded):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "speech_translate\utils\Record.py", line 776, in run_threaded
  File "whisper\transcribe.py", line 84, in transcribe
  File "whisper\audio.py", line 111, in log_mel_spectrogram
  File "whisper\audio.py", line 42, in load_audio
  File "ffmpeg\_run.py", line 313, in run
  File "ffmpeg\_run.py", line 284, in run_async
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
T

**Comment by Dadangdut33** [comment]
thanks for the issue submission, It seems that the problem is caused by ffmpeg not installed on your system just like in #12.

To fix this you need to have it installed. You can follow the instruction in [the user requirements in the readme](https://github.com/Dadangdut33/Speech-Translate#user-requirements).

i'll be sure to add an onboarding for the app on the next update so the user won't miss this part
