### ISSUE TITLE
Application hang due to: FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by PhyrexianHulk** [Dadangdut33/Speech-Translate#61]
Only interested in transcription.
Open application.
Mode: Transcribe
Model: Base
TL Engine: Whisper or Google

Click "Import From File".
Choose an mp4 file from my drive.

Output from command prompt window:

...
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2023-12-19 08:53:06,476 INFO    - Booting up... (Main.py:959) [MainThread]
2023-12-19 08:53:06,478 DEBUG   - Got console window (Main.py:962) [MainThread]
2023-12-19 08:53:08,098 INFO    - Checking for update on start (About.py:108) [MainThread]
2023-12-19 08:53:08,160 INFO    - Checking for update... (About.py:133) [MainThread]
2023-12-19 08:53:08,682 INFO    - New version found: 1.3.7 (About.py:146) [Thread-3 (req_update_check)]
2023-12-19 08:53:44,877 INFO    - Start Process (FILE) (Record.py:848) [Thread-5 (from_file)]
2023-12-19 08:53:45,199 INFO    - -------------------------------------------------- (Record.py:761) [Thread-6 (multiproc_tc)]
2023-12-19 08:53:45,199 INFO    - Transcribing Audio: C:/Users/zlazi/Downloads/next-gen-hacker.mp4 (Record.py:762) [Thread-6 (multiproc_tc)]
2023-12-19 08:53:45,200 DEBUG   - Source Language: Auto (Record.py:771) [Thread-6 (multiproc_tc)]
Exception in thread Thread-7 (run_threaded):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "speech_translate\utils\Record.py", line 776, in run_threaded
  File "whisper\transcribe.py", line 84, in transcribe
  File "whisper\audio.py", line 111, in log_mel_spectrogram
  File "whisper\audio.py", line 42, in load_audio
  File "ffmpeg\_run.py", line 313, in run
  File "ffmpeg\_run.py", line 284, in run_async
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-12-19 08:54:55,037 INFO    - Cancelling file import processing... (Main.py:937) [MainThread]
2023-12-19 08:54:55,115 INFO    - End process (FILE) [Total time: 70.24s] (Record.py:906) [Thread-5 (from_file)]

**Comment by Dadangdut33** [comment]
What version of the app are you using? It seems like  it's one of the very old version. Update it first please

Also the error is because you haven't installed and add ffmpeg to your path. This is needed in the older version (below 1.3.6)

**Comment by PhyrexianHulk** [comment]
Yes. It was definitely an older version. Thanks.
The latest version is working perfectly.
