### ISSUE TITLE
[BUG]  Error when activating Debug recording

### ISSUE THREAD

**Issue by DenisMartin0** [Dadangdut33/Speech-Translate#64]
When activating the "Debug Recording" option (see below), it generate an error when starting a recording session.

![image](https://github.com/Dadangdut33/Speech-Translate/assets/36104617/0192f2c1-fe15-4462-ae8e-b820cc2c307b)

![image](https://github.com/Dadangdut33/Speech-Translate/assets/36104617/289c4bc1-466c-4a1e-a453-656adf37bcd4)

Error log is:
2024-01-01 20:35:11.178 | ERROR   | record.py:944 [Thread-28 (record_session)] - TypedDict does not support instance and class checks
Traceback (most recent call last):
  File "D:\Codes\_Projects\Python\Speech-Translate\speech_translate\utils\audio\record.py", line 860, in record_session
  File "D:\Codes\_Projects\Python\Speech-Translate\speech_translate\utils\whisper\helper.py", line 57, in stablets_verbose_log
  File "C:\Users\PC\.pyenv\pyenv-win\versions\3.11.6\Lib\typing.py", line 3010, in subclasscheck
TypeError: TypedDict does not support instance and class checks

It seems that it comes from a call to isinstance in helper.py
**record.py**
![image](https://github.com/Dadangdut33/Speech-Translate/assets/36104617/62b14108-c013-456b-aba6-78f095d90df0)

**helper.py**
![image](https://github.com/Dadangdut33/Speech-Translate/assets/36104617/c0baa029-c0e6-40f8-a6a6-2b3ec66624f5)

**Comment by Dadangdut33** [comment]
got it thanks for the bug report

**Comment by Dadangdut33** [comment]
fixed in https://github.com/Dadangdut33/Speech-Translate/releases/tag/1.3.9
