### ISSUE TITLE
Downloads not working.

### ISSUE THREAD

**Issue by jamman83** [Dadangdut33/Speech-Translate#80]
When trying to download the whisper models and the model directory is changed manually, it will fail to start the download with the following log:

2024-06-15 18:48:16.623 | DEBUG   | download.py:378 [Thread-25 (download_model)] - Downloading model from Hugging Face Hub
2024-06-15 18:48:16.623 | ERROR   | _logging.py:62 [Thread-25 (download_model)] - Exception in thread
2024-06-15 18:48:16.623 | ERROR   | _logging.py:62 [Thread-25 (download_model)] - Thread-25 (download_model)
2024-06-15 18:48:16.623 | ERROR   | _logging.py:62 [Thread-25 (download_model)] - :
2024-06-15 18:48:16.623 | ERROR   | _logging.py:62 [Thread-25 (download_model)] - Traceback (most recent call last):
2024-06-15 18:48:16.623 | ERROR   | _logging.py:62 [Thread-25 (download_model)] -   File "C:\Users\PC\.pyenv\pyenv-win\versions\3.11.6\Lib\threading.py", line 1045, in _bootstrap_inner
2024-06-15 18:48:16.623 | ERROR   | _logging.py:62 [Thread-25 (download_model)] -   File "C:\Users\PC\.pyenv\pyenv-win\versions\3.11.6\Lib\threading.py", line 982, in run
2024-06-15 18:48:16.623 | ERROR   | _logging.py:62 [Thread-25 (download_model)] -   File "D:\Codes\_Projects\Python\Speech-Translate\speech_translate\utils\whisper\download.py", line 44, in download_model
2024-06-15 18:48:16.633 | ERROR   | _logging.py:62 [Thread-25 (download_model)] -   File "D:\Codes\_Projects\Python\Speech-Translate\speech_translate\ui\custom\download.py", line 379, in faster_whisper_download_with_progress_gui
2024-06-15 18:48:16.634 | ERROR   | _logging.py:62 [Thread-25 (download_model)] -   File "<frozen os>", line 210, in makedirs
2024-06-15 18:48:16.634 | ERROR   | _logging.py:62 [Thread-25 (download_model)] -   File "<frozen ntpath>", line 213, in split
2024-06-15 18:48:16.634 | ERROR   | _logging.py:62 [Thread-25 (download_model)] - TypeError
2024-06-15 18:48:16.634 | ERROR   | _logging.py:62 [Thread-25 (download_model)] - :
2024-06-15 18:48:16.634 | ERROR   | _logging.py:62 [Thread-25 (download_model)] - expected str, bytes or os.PathLike object, not `tuple`

setting the directory back to default allowed me to download and the manually move it, but it would be nice to save my poor nvme a little space.

**Comment by tuzibr** [comment]
Thankyou，I cant download anything model since i change the model directory
